### ISSUE TITLE
GPLOT Polar fails while attempting to calculate vortex depth

### ISSUE THREAD

**Issue by ghassan-alaka** [ghassan-alaka/GPLOT#51]
This issue causes a fatal error in GPLOT polar (**polar_cylindrical_structure.py**) for the following command on RDHPCS Jet:
```python /home/Ghassan.Alaka/GPLOT/sorc/GPLOT/python/polar_cylindrical_structure.py 2023041318 18S polar Tier1 XX False 1.5 600 46 /home/Ghassan.Alaka/GPLOT/parm/namelist.master.HWRF_Forecast```

Here is the error:
```Traceback (most recent call last):
  File "/home/Ghassan.Alaka/GPLOT/sorc/GPLOT/python/polar_cylindrical_structure.py", line 2742, in <module>
    main()
  File "/home/Ghassan.Alaka/GPLOT/sorc/GPLOT/python/polar_cylindrical_structure.py", line 1293, in main
    vortex_depth_vort = np.min(heightlevs[np.argwhere(vort_ratio[5::] < threshold_ratio_vort)+5])/1000
  File "<__array_function__ internals>", line 6, in amin
  File "/mnt/lfs1/HFIP/hur-aoml/Ghassan.Alaka/miniconda3/envs/GPLOT/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/mnt/lfs1/HFIP/hur-aoml/Ghassan.Alaka/miniconda3/envs/GPLOT/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity```

**Comment by AndrewHazelton** [comment]
@ghassan-alaka I just pushed a fix for this to develop.

**Comment by ghassan-alaka** [comment]
This issue was fixed in the following commit:
https://github.com/ghassan-alaka/GPLOT/commit/24148164c126a805c92f5fa149044f4646ba656a
